import fs from "node:fs";
import path from "node:path";
import {
  createPhaseRun,
  createReviewComment,
  getProject,
  updatePhaseRun,
  updateProjectAuditorModelConfig,
  updateProjectImageGenerationEnabled,
  updateProjectImageModelConfig,
  updateProjectPhase
} from "@/lib/db";
import {
  copyProductTemplateToProject,
  getExtractedMaterialsForProduct,
  saveProductTemplate
} from "@/lib/productTemplates";
import {
  getInputsDir,
  getOutputsDir,
  getProjectDir,
  readOutputForPhase,
  readProjectFile,
  resolveProjectFile,
  writeArticleBrief
} from "@/lib/fileStorage";
import {
  approvePhaseInState,
  readProjectState,
  rewindToPhase4AfterPhase5Revision,
  setPhaseStatus,
  updateAuditorModelInState,
  writeProjectState
} from "@/lib/projectState";
import {
  approveAllImages,
  approveImage as approveImageInReview,
  markImageNeedsRevision,
  resetImageReviewForGeneratedImages
} from "@/lib/imageReview";
import { getSkillDir, runPythonScript, runSkillPrompt, buildImageEnv, buildModelEnv } from "@/lib/codexClient";
import { resolveTextModel } from "@/lib/modelCatalog";
import { ImageProvider, PhaseId, Project, Provider } from "@/lib/types";
import {
  assertPhaseCanApprove,
  assertPhaseCanRun,
  phaseLabels,
  phaseOutputs,
  requiresManualReview,
  resolveImageModelSelection,
  sanitizeError
} from "@/lib/validators";

const promptFiles: Record<PhaseId, string> = {
  phase0: "phase0_read_materials.md",
  phase1: "phase1_outline.md",
  phase2: "phase2_first_two_sections.md",
  phase3: "phase3_full_article.md",
  phase4: "phase4_checklist.md",
  phase5: "phase5_final_delivery.md"
};

const phase4ChunkMaxChars = 2500;
const DEFAULT_MIN_WORDS = 1200;
const DEFAULT_MAX_WORDS = 1600;

/** Extract word count range from project extraNotes (set by cluster creation) */
function getWordCountRange(projectId: string): { min: number; max: number } {
  try {
    const state = readProjectState(projectId);
    const extraNotes = state.inputs.articleBrief.extraNotes || "";
    const match = extraNotes.match(/Target Words:\s*(\d+)-(\d+)/);
    if (match) {
      return { min: parseInt(match[1], 10), max: parseInt(match[2], 10) };
    }
  } catch {
    // ignore
  }
  return { min: DEFAULT_MIN_WORDS, max: DEFAULT_MAX_WORDS };
}

export function getProjectState(projectId: string) {
  return readProjectState(projectId);
}

export function getPhaseOutput(projectId: string, phase: PhaseId): string {
  return readOutputForPhase(projectId, phase);
}

function requireProject(projectId: string): Project {
  const project = getProject(projectId);
  if (!project) {
    throw new Error("项目不存在");
  }
  return project;
}

function skillPath(...parts: string[]): string {
  return path.join(getSkillDir(), ...parts);
}

function outputPath(projectId: string, filename: string): string {
  return path.join(getOutputsDir(projectId), filename);
}

const imageExampleExtensions = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif"]);

function languageContentRequirementsPath(): string {
  return skillPath("references", "language_content_requirements.md");
}

function buildBriefMarkdown(project: Project): string {
  const state = readProjectState(project.id);
  const brief = state.inputs.articleBrief;
  const wordRange = getWordCountRange(project.id);
  return [
    "# Article Brief",
    "",
    `- Project name: ${project.name}`,
    `- Article title: ${project.article_title || "To be generated by SEO Article Writer Skill in Phase 1."}`,
    `- Topic: ${project.topic}`,
    `- Primary keyword: ${project.primary_keyword}`,
    `- Secondary keywords: ${project.secondary_keywords || "To be generated by SEO Article Writer Skill in Phase 1 based on the primary keyword, search intent, examples, and writing guidelines."}`,
    `- Article focus: ${project.article_focus}`,
    `- Recommendation reason: ${project.recommendation_reason}`,
    `- Target audience: ${project.target_audience || "To be inferred by SEO Article Writer Skill from the brief, keywords, examples, and writing guidelines."}`,
    `- Search intent: ${project.search_intent || "To be inferred by SEO Article Writer Skill during Phase 0 / Phase 1."}`,
    `- Language: ${project.language}`,
    `- Brand name: ${project.brand_name}`,
    `- Target word count: ${wordRange.min}-${wordRange.max} visible article words, counting headings, body, tables, and FAQ, excluding SEO metadata, prompts, checklist reports, and image planning files.`,
    `- Deferred image requirements for Phase 5.5 only: ${brief.imageRequirements}`,
    `- Extra notes: ${brief.extraNotes || "None"}`
  ].join("\n");
}

function buildInvocationPrompt(projectId: string, phase: PhaseId): string {
  const projectPath = getProjectDir(projectId);
  const outputNames = phaseOutputs[phase].join(", ");
  return [
    `请使用 SEO Article Writer Skill 执行 ${phase.toUpperCase()}：${phaseLabels[phase]}。`,
    `项目目录为：${projectPath}`,
    `请读取 inputs 和 outputs 中已经存在的材料。`,
    `请输出：${outputNames}`,
    "完成本阶段后停止，不要自动进入下一阶段。"
  ].join("\n");
}

function commonPromptArgs(projectId: string, phase: PhaseId, inputs: string[], output: string): string[] {
  return [
    skillPath("scripts", "run_prompt.py"),
    "--prompt",
    skillPath("prompts", promptFiles[phase]),
    "--input",
    skillPath("SKILL.md"),
    "--input",
    skillPath("workflow.md"),
    ...inputs.flatMap((input) => ["--input", input]),
    "--output",
    output
  ];
}

function phase0ChecklistPromptArgs(inputs: string[], output: string): string[] {
  return [
    skillPath("scripts", "run_prompt.py"),
    "--prompt",
    skillPath("prompts", "phase0_generate_checklist.md"),
    "--input",
    skillPath("SKILL.md"),
    "--input",
    skillPath("workflow.md"),
    "--input",
    languageContentRequirementsPath(),
    ...inputs.flatMap((input) => ["--input", input]),
    "--output",
    output
  ];
}

function phase2AuditorPolishPromptArgs(inputs: string[], output: string): string[] {
  return [
    skillPath("scripts", "run_prompt.py"),
    "--prompt",
    skillPath("prompts", "phase2_auditor_polish.md"),
    "--input",
    skillPath("SKILL.md"),
    "--input",
    skillPath("workflow.md"),
    "--input",
    languageContentRequirementsPath(),
    ...inputs.flatMap((input) => ["--input", input]),
    "--output",
    output
  ];
}

function phase4PromptArgs(promptFile: string, inputs: string[], output: string): string[] {
  return [
    skillPath("scripts", "run_prompt.py"),
    "--prompt",
    skillPath("prompts", promptFile),
    ...inputs.flatMap((input) => ["--input", input]),
    "--output",
    output
  ];
}

function promptArgs(promptFile: string, inputs: string[], output: string): string[] {
  return [
    skillPath("scripts", "run_prompt.py"),
    "--prompt",
    skillPath("prompts", promptFile),
    "--input",
    skillPath("SKILL.md"),
    "--input",
    skillPath("workflow.md"),
    ...inputs.flatMap((input) => ["--input", input]),
    "--output",
    output
  ];
}

function getInputSources(projectId: string): string[] {
  const state = readProjectState(projectId);
  const inputs = [
    state.inputs.writingGuidelineFile,
    ...state.inputs.exampleArticleFiles,
    state.inputs.topicRequirementFile
  ].filter(Boolean);
  if (!state.inputs.writingGuidelineFile) {
    throw new Error("写作规范不存在，请先上传 writingGuidelineFile。");
  }
  return inputs.map((relativePath) => resolveProjectFile(projectId, relativePath));
}

async function runPhase0(project: Project): Promise<string> {
  const outputsDir = getOutputsDir(project.id);
  fs.mkdirSync(outputsDir, { recursive: true });
  const extractedPath = outputPath(project.id, "extracted_materials.md");
  const briefPath = path.join(getInputsDir(project.id), "article_brief.md");
  writeArticleBrief(project.id, buildBriefMarkdown(project));

  const productName = (project.brand_name || "").trim();
  const templatePath = productName ? getExtractedMaterialsForProduct(productName) : null;

  if (templatePath && fs.existsSync(templatePath)) {
    fs.copyFileSync(templatePath, extractedPath);
  } else {
    await runPythonScript(
      [skillPath("scripts", "extract_materials.py"), ...getInputSources(project.id), "-o", extractedPath],
      { cwd: getSkillDir(), env: buildModelEnv(project), timeoutMs: 180000 }
    );
    if (productName && fs.existsSync(extractedPath)) {
      saveProductTemplate(productName, extractedPath, getInputSources(project.id));
    }
  }

  const output = outputPath(project.id, phaseOutputs.phase0[0]);
  await runSkillPrompt(
    project,
    commonPromptArgs(project.id, "phase0", [extractedPath, briefPath], output)
  );
  const checklist = outputPath(project.id, phaseOutputs.phase0[1]);
  await runSkillPrompt(
    project,
    phase0ChecklistPromptArgs([extractedPath, briefPath, output], checklist)
  );
  ensureOutputExists(checklist);
  return output;
}

async function runPhase5(project: Project): Promise<string> {
  const confirmation = outputPath(project.id, "phase5_final_delivery.md");
  const summary = outputPath(project.id, "00_material_reading_summary.md");
  const full = outputPath(project.id, "03_full_article.md");
  const checklist = outputPath(project.id, "04_checklist_report.md");
  await runSkillPrompt(project, commonPromptArgs(project.id, "phase5", [summary, full, checklist], confirmation));
  normalizeMarkdownOutput(confirmation);
  const docx = await generateFinalDocx(project);
  if (!fs.existsSync(confirmation) || !fs.existsSync(docx)) {
    throw new Error("Phase 5 输出文件未生成完整。");
  }
  return docx;
}

async function generateFinalDocx(project: Project, useSlotArticle = false): Promise<string> {
  const slotArticle = outputPath(project.id, "final_article_with_image_slots.md");
  const fullArticle = normalizeFinalArticleForDelivery(project);
  const articlePath = useSlotArticle && fs.existsSync(slotArticle) ? slotArticle : fullArticle;
  const imagePlanPath = outputPath(project.id, "image_plan.json");
  const docx = outputPath(project.id, "final_article_for_google_docs.docx");
  const args = [skillPath("scripts", "generate_docx.py"), articlePath, docx];
  if (fs.existsSync(imagePlanPath)) {
    args.push("--image-plan", imagePlanPath);
  }
  // Pass base-url for cluster articles with INTERNAL_LINK placeholders
  try {
    const { getClusterForProject } = await import("@/lib/db");
    const cluster = getClusterForProject(project.id);
    if (cluster?.blog_base_url) {
      args.push("--base-url", cluster.blog_base_url);
    }
  } catch { /* not a cluster project, skip */ }
  await runPythonScript(args, {
    cwd: getSkillDir(),
    env: buildModelEnv(project),
    timeoutMs: 120000
  });
  if (!fs.existsSync(docx)) {
    throw new Error("最终 Word 文件未生成。");
  }
  return docx;
}

function buildImageGenerationConfig(project: Project) {
  const imageProvider = project.image_provider || "volcengine_ark";
  const { imageModelDisplayName, imageModelId } = resolveImageModelSelection(
    imageProvider,
    project.image_model_display_name || project.image_model_name || "",
    project.image_model_id || ""
  );
  const imageEndpointId = project.image_endpoint_id || "";
  const useEndpointId = Boolean(Number(project.image_use_endpoint_id));
  const finalModelForRequest = useEndpointId ? imageEndpointId : imageModelId;
  const legacyModelForRequest =
    imageProvider === "volcengine_ark" || imageProvider === "doubao"
      ? finalModelForRequest
      : imageModelId || imageModelDisplayName;
  return {
    enabled: Boolean(Number(project.enable_image_generation)),
    provider: imageProvider,
    api_type:
      imageProvider === "volcengine_ark" || imageProvider === "doubao"
        ? "volcengine_ark_images_generations"
        : `${imageProvider}_images`,
    model_display_name: imageModelDisplayName,
    image_model_display_name: imageModelDisplayName,
    model: legacyModelForRequest,
    model_id: imageModelId,
    image_model_id: imageModelId,
    endpoint_id: imageEndpointId,
    image_endpoint_id: imageEndpointId,
    use_endpoint_id: useEndpointId,
    base_url: project.image_base_url || "",
    temperature: Number(project.image_temperature ?? 0.2),
    skill_path: project.image_skill_path || "../skills/hellotalk-blog-image-planner-v2.skill",
    output_format: project.image_output_format || "png",
    default_aspect_ratio: project.image_aspect_ratio_default || "16:9",
    retry_count: Number(project.image_retry_count ?? 2),
    insert_mode: project.image_insert_mode || "placeholder",
    default_image_count: Number(project.image_count_default ?? 3),
    allow_non_compliant_images: Boolean(Number(project.image_allow_non_compliant_images)),
    caption_enabled: false
  };
}

function writeImageGenerationConfig(project: Project): string {
  const configPath = outputPath(project.id, "image_generation_config.json");
  fs.writeFileSync(configPath, JSON.stringify(buildImageGenerationConfig(project), null, 2), "utf-8");
  return configPath;
}

function writeImagePlanningProjectConfig(project: Project, imageStyleExamplesManifestPath = ""): string {
  const state = readProjectState(project.id);
  const configPath = outputPath(project.id, "image_planning_project_config.json");
  fs.writeFileSync(
    configPath,
    JSON.stringify(
      {
        project_name: project.name,
        article_title: project.article_title,
        topic: project.topic,
        primary_keyword: project.primary_keyword,
        secondary_keywords: project.secondary_keywords,
        article_focus: project.article_focus,
        recommendation_reason: project.recommendation_reason,
        target_audience: project.target_audience,
        search_intent: project.search_intent,
        language: project.language,
        brand_name: project.brand_name,
        deferred_image_requirements: state.inputs.articleBrief.imageRequirements,
        extra_notes: state.inputs.articleBrief.extraNotes,
        image_style_examples_manifest: imageStyleExamplesManifestPath,
        image_generation: buildImageGenerationConfig(project)
      },
      null,
      2
    ),
    "utf-8"
  );
  return configPath;
}

function imageExamplesRoot(): string {
  const configured = process.env.IMAGE_EXAMPLES_DIR || "../examples";
  return path.isAbsolute(configured) ? configured : path.resolve(process.cwd(), configured);
}

function walkFiles(root: string): string[] {
  if (!fs.existsSync(root)) {
    return [];
  }
  const files: string[] = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkFiles(fullPath));
    } else if (entry.isFile()) {
      files.push(fullPath);
    }
  }
  return files;
}

function readUInt24LE(buffer: Buffer, offset: number): number {
  return buffer[offset] + (buffer[offset + 1] << 8) + (buffer[offset + 2] << 16);
}

function imageDimensions(filePath: string): string {
  try {
    const buffer = fs.readFileSync(filePath);
    if (buffer.length >= 24 && buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
      return `${buffer.readUInt32BE(16)}x${buffer.readUInt32BE(20)}`;
    }
    if (buffer.length >= 12 && buffer.subarray(0, 4).toString("ascii") === "RIFF" && buffer.subarray(8, 12).toString("ascii") === "WEBP") {
      const chunk = buffer.subarray(12, 16).toString("ascii");
      if (chunk === "VP8X" && buffer.length >= 30) {
        return `${readUInt24LE(buffer, 24) + 1}x${readUInt24LE(buffer, 27) + 1}`;
      }
      if (chunk === "VP8L" && buffer.length >= 25) {
        const bits = buffer[21] | (buffer[22] << 8) | (buffer[23] << 16) | (buffer[24] << 24);
        return `${(bits & 0x3fff) + 1}x${((bits >> 14) & 0x3fff) + 1}`;
      }
      if (chunk === "VP8 ") {
        const startCode = Buffer.from([0x9d, 0x01, 0x2a]);
        const index = buffer.indexOf(startCode, 20);
        if (index >= 0 && buffer.length >= index + 7) {
          const width = buffer.readUInt16LE(index + 3) & 0x3fff;
          const height = buffer.readUInt16LE(index + 5) & 0x3fff;
          return `${width}x${height}`;
        }
      }
    }
    if (buffer.length > 4 && buffer[0] === 0xff && buffer[1] === 0xd8) {
      let offset = 2;
      while (offset < buffer.length) {
        if (buffer[offset] !== 0xff) {
          offset += 1;
          continue;
        }
        const marker = buffer[offset + 1];
        const length = buffer.readUInt16BE(offset + 2);
        if (marker >= 0xc0 && marker <= 0xc3 && buffer.length >= offset + 9) {
          return `${buffer.readUInt16BE(offset + 7)}x${buffer.readUInt16BE(offset + 5)}`;
        }
        offset += 2 + length;
      }
    }
  } catch {
    return "";
  }
  return "";
}

function tagsFromFilename(filePath: string): string {
  return path
    .basename(filePath, path.extname(filePath))
    .split(/[-_\s]+/)
    .map((item) => item.trim())
    .filter(Boolean)
    .join(", ");
}

function writeImageStyleReferenceExamples(project: Project): string {
  const examplesRoot = imageExamplesRoot();
  const output = outputPath(project.id, "image_style_reference_examples.md");
  const imageFiles = walkFiles(examplesRoot)
    .filter((filePath) => imageExampleExtensions.has(path.extname(filePath).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, "en"))
    .slice(0, 50);

  const lines = [
    "# Image Style Reference Examples",
    "",
    "Use these local image examples as style and composition references during Phase 5.5 planning.",
    "Do not copy exact artwork, visible text, UI copy, or unsupported claims from these examples.",
    "Do not copy logos or wordmarks from reference examples.",
    "Translate the reusable visual traits into concrete prompt language: photorealistic generated learner, brand purple, soft bright background, phone mockup, purple chat bubbles, rounded cards, visual hierarchy, and article-specific composition.",
    "If an example conflicts with the active HelloTalk image policy, the policy wins.",
    "",
    `Examples root: ${examplesRoot}`,
    ""
  ];

  if (imageFiles.length === 0) {
    lines.push("No image examples were found.");
  } else {
    lines.push("| File | Relative path | Dimensions | Size | Filename tags |");
    lines.push("|---|---|---:|---:|---|");
    for (const filePath of imageFiles) {
      const stats = fs.statSync(filePath);
      const relativePath = path.relative(examplesRoot, filePath).replace(/\\/g, "/");
      const dimensions = imageDimensions(filePath) || "unknown";
      const sizeKb = `${Math.max(1, Math.round(stats.size / 1024))} KB`;
      lines.push(`| ${path.basename(filePath)} | ${relativePath} | ${dimensions} | ${sizeKb} | ${tagsFromFilename(filePath)} |`);
    }
  }

  fs.writeFileSync(output, lines.join("\n") + "\n", "utf-8");
  return output;
}

function resolveOptionalPath(raw: string, projectDir: string, outputsDir: string): string {
  const candidates = [
    raw,
    path.join(projectDir, raw),
    path.join(outputsDir, raw),
    path.resolve(process.cwd(), raw),
    path.resolve(process.cwd(), "..", raw)
  ].map((candidate) => path.resolve(candidate));
  const found = candidates.find((candidate) => fs.existsSync(candidate));
  if (!found) {
    throw new Error(`image_skill_path not found: ${raw}`);
  }
  return found;
}

function existingSkillInputs(skillDir: string): string[] {
  return [
    path.join(skillDir, "SKILL.md"),
    path.join(skillDir, "references", "prompt-templates.md"),
    path.join(skillDir, "references", "style-guide.md"),
    path.join(skillDir, "references", "ui-screenshot-guide.md")
  ].filter((candidate) => fs.existsSync(candidate));
}

async function runPhase55ImagePlanning(project: Project, configPath: string): Promise<void> {
  const outputsDir = getOutputsDir(project.id);
  const projectDir = getProjectDir(project.id);
  const articleMd = outputPath(project.id, "03_full_article.md");
  const rawPlan = outputPath(project.id, "image_plan_raw.md");
  const imageStyleExamplesManifest = writeImageStyleReferenceExamples(project);
  const planningProjectConfig = writeImagePlanningProjectConfig(project, imageStyleExamplesManifest);
  const skillDir = resolveOptionalPath(
    project.image_skill_path || "../skills/hellotalk-blog-image-planner-v2.skill",
    projectDir,
    outputsDir
  );
  const promptPath = skillPath("prompts", "phase5_5_image_planning.md");

  await runPythonScript(
    [
      skillPath("scripts", "run_prompt.py"),
      "--prompt",
      promptPath,
      ...existingSkillInputs(skillDir).flatMap((input) => ["--input", input]),
      "--input",
      planningProjectConfig,
      "--input",
      imageStyleExamplesManifest,
      "--input",
      configPath,
      "--input",
      articleMd,
      "--output",
      rawPlan
    ],
    { cwd: getSkillDir(), env: buildModelEnv(project, "writing"), timeoutMs: 600000 }
  );

  await runPythonScript(
    [
      path.join(process.cwd(), "scripts", "phase5_5_image_planning.py"),
      "--raw-plan",
      rawPlan,
      "--article-md",
      articleMd,
      "--config",
      configPath,
      "--output-dir",
      outputsDir
    ],
    { cwd: process.cwd(), env: buildModelEnv(project, "writing"), timeoutMs: 120000 }
  );
  ensureOutputExists(outputPath(project.id, "image_plan.json"));
  ensureOutputExists(outputPath(project.id, "final_article_with_image_slots.md"));
}

async function runPhase6ImageOutput(
  project: Project,
  options: {
    mode?: "all" | "generate" | "insert";
    onlyImageId?: string;
    reviewComment?: string;
  } = {}
): Promise<void> {
  const outputsDir = getOutputsDir(project.id);
  const finalDocx = outputPath(project.id, "final_article_for_google_docs.docx");
  const configPath = writeImageGenerationConfig(project);
  const scriptPath = path.join(process.cwd(), "scripts", "phase6_image_generation.py");
  const logPath = outputPath(project.id, "phase6.log");
  const mode = options.mode || "all";
  const args = [
    scriptPath,
    "--config",
    configPath,
    "--project-dir",
    getProjectDir(project.id),
    "--final-docx",
    finalDocx,
    "--article-md",
    outputPath(project.id, "final_article_with_image_slots.md"),
    "--image-plan",
    outputPath(project.id, "image_plan.json"),
    "--output-dir",
    outputsDir,
    "--mode",
    mode
  ];
  if (options.onlyImageId) {
    args.push("--only-image-id", options.onlyImageId);
  }
  if (options.reviewComment) {
    args.push("--review-comment", options.reviewComment);
  }

  try {
    await runPythonScript(
      args,
      { cwd: process.cwd(), env: buildImageEnv(project), timeoutMs: 900000 }
    );
  } catch (error) {
    const message = sanitizeError(error);
    fs.appendFileSync(
      logPath,
      [
        `[${new Date().toISOString()}] Phase 6 runner failed before graceful completion.`,
        message,
        ""
      ].join("\n"),
      "utf-8"
    );
    const fallbackDocx = outputPath(project.id, "final_article_with_images.docx");
    if (mode === "all" && fs.existsSync(finalDocx) && !fs.existsSync(fallbackDocx)) {
      fs.copyFileSync(finalDocx, fallbackDocx);
    }
  }
}

export async function retryImageGeneration(projectId: string): Promise<void> {
  const project = requireProject(projectId);
  await runPhase6ImageOutput(project, { mode: "generate" });
  resetImageReviewForGeneratedImages(project.id);
}

export async function changeImageModelAndRetry(projectId: string, config: {
  provider: ImageProvider;
  modelDisplayName: string;
  modelId: string;
  endpointId: string;
  useEndpointId: boolean;
}): Promise<void> {
  updateProjectImageModelConfig(projectId, config);
  const state = readProjectState(projectId);
  state.modelConfig.imageGeneration.provider = config.provider;
  state.modelConfig.imageGeneration.modelDisplayName = config.modelDisplayName;
  state.modelConfig.imageGeneration.modelName = config.modelDisplayName;
  state.modelConfig.imageGeneration.modelId = config.modelId;
  state.modelConfig.imageGeneration.endpointId = config.endpointId;
  state.modelConfig.imageGeneration.useEndpointId = config.useEndpointId;
  writeProjectState(state);
  await retryImageGeneration(projectId);
}

export function setImageGenerationEnabled(projectId: string, enabled: boolean): void {
  updateProjectImageGenerationEnabled(projectId, enabled);
  const state = readProjectState(projectId);
  state.modelConfig.imageGeneration.enabled = enabled;
  writeProjectState(state);
}

export async function startImageGeneration(projectId: string): Promise<void> {
  const project = requireProject(projectId);
  const configPath = writeImageGenerationConfig(project);
  const planPath = outputPath(projectId, "image_plan.json");
  if (!fs.existsSync(planPath)) {
    await runPhase55ImagePlanning(project, configPath);
  }
  if (!Boolean(Number(project.enable_image_generation))) {
    setImageGenerationEnabled(projectId, true);
  }
  await runPhase6ImageOutput(project, { mode: "generate" });
  resetImageReviewForGeneratedImages(projectId);
}

function clearPhase4AuditReports(projectId: string): void {
  const checklistReport = outputPath(projectId, phaseOutputs.phase4[0]);
  if (fs.existsSync(checklistReport)) {
    fs.unlinkSync(checklistReport);
  }

  const chunkDir = path.join(getOutputsDir(projectId), "phase4_audit_chunks");
  if (!fs.existsSync(chunkDir)) {
    return;
  }

  for (const entry of fs.readdirSync(chunkDir, { withFileTypes: true })) {
    if (entry.isFile() && /^chunk_\d+_report\.md$/.test(entry.name)) {
      fs.unlinkSync(path.join(chunkDir, entry.name));
    }
  }
}

function phase4AuditReportPaths(projectId: string): string[] {
  const paths: string[] = [];
  const checklistReport = outputPath(projectId, phaseOutputs.phase4[0]);
  if (fs.existsSync(checklistReport)) {
    paths.push(checklistReport);
  }

  const chunkDir = path.join(getOutputsDir(projectId), "phase4_audit_chunks");
  if (fs.existsSync(chunkDir)) {
    const chunkReports = fs
      .readdirSync(chunkDir, { withFileTypes: true })
      .filter((entry) => entry.isFile() && /^chunk_\d+_report\.md$/.test(entry.name))
      .map((entry) => path.join(chunkDir, entry.name))
      .sort((a, b) => a.localeCompare(b, "en"));
    paths.push(...chunkReports);
  }

  return paths;
}

function compactAuditLine(line: string): string {
  return line
    .replace(/^#{1,6}\s+/, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 700);
}

function writePhase5RevisionAuditSummary(projectId: string): string {
  const reportPaths = phase4AuditReportPaths(projectId);
  if (reportPaths.length === 0) {
    return "";
  }

  const lines = [
    "# Phase 4 Audit Summary For Revision",
    "",
    "This summary contains only audit issues and questions. It intentionally excludes old article body chunks.",
    "When revising, use only the current latest `03_full_article.md` as the article body source.",
    ""
  ];
  let issueCount = 0;
  let questionCount = 0;

  for (const reportPath of reportPaths) {
    const report = fs.readFileSync(reportPath, "utf-8");
    const issues = meaningfulIssueLines(report)
      .map(compactAuditLine)
      .filter((line) => line && !/^chunk\s+\d+/i.test(line))
      .slice(0, 20);
    const questions = remainingQuestionLines(report)
      .map(compactAuditLine)
      .filter((line) => line && !/^chunk\s+\d+/i.test(line))
      .slice(0, 10);

    if (issues.length === 0 && questions.length === 0) {
      continue;
    }

    lines.push(`## ${path.basename(reportPath)}`, "");
    if (issues.length > 0) {
      lines.push("### Issues", ...issues.map((issue) => `- ${issue}`), "");
      issueCount += issues.length;
    }
    if (questions.length > 0) {
      lines.push("### Remaining Questions", ...questions.map((question) => `- ${question}`), "");
      questionCount += questions.length;
    }
  }

  if (issueCount === 0 && questionCount === 0) {
    lines.push("- No explicit unresolved Phase 4 issues were found in the reports. Apply only the human review comment and fixed checklist.", "");
  }

  const summaryPath = outputPath(projectId, "phase5_revision_audit_summary.md");
  fs.writeFileSync(summaryPath, lines.join("\n").trimEnd() + "\n", "utf-8");
  return summaryPath;
}

function clearDeliveryOutputs(projectId: string): void {
  const outputsDir = getOutputsDir(projectId);
  const staleFiles = [
    "phase5_final_delivery.md",
    "final_article_for_google_docs.docx",
    "final_article_with_image_slots.md",
    "final_article_with_images.docx",
    "image_style_reference_examples.md",
    "image_plan_raw.md",
    "image_plan.json",
    "image_planning_project_config.json",
    "image_generation_config.json",
    "image_planning.log",
    "image_metadata.json",
    "image_review.json",
    "image_compliance_report.json",
    "phase6.log",
    "images.json"
  ];

  for (const file of staleFiles) {
    const target = path.join(outputsDir, file);
    if (fs.existsSync(target)) {
      fs.unlinkSync(target);
    }
  }

  fs.rmSync(path.join(outputsDir, "images"), { recursive: true, force: true });
}

export async function changeAuditorModelAndRetry(projectId: string, config: {
  provider: Provider;
  modelName: string;
  baseUrl: string;
  temperature: number;
}): Promise<void> {
  const modelName = config.modelName.trim();
  if (!modelName) {
    throw new Error("审查模型不能为空。");
  }
  const temperature = Number.isFinite(config.temperature) ? config.temperature : 0.2;
  const nextConfig = {
    provider: config.provider,
    modelName: resolveTextModel(config.provider, modelName),
    baseUrl: config.baseUrl.trim(),
    temperature
  };
  updateProjectAuditorModelConfig(projectId, nextConfig);
  updateAuditorModelInState(projectId, nextConfig);
  clearPhase4AuditReports(projectId);
  await runPhase(projectId, "phase4");
}

export function approveGeneratedImage(projectId: string, imageId: string): void {
  approveImageInReview(projectId, imageId);
}

export async function regenerateGeneratedImage(projectId: string, imageId: string, reviewComment: string): Promise<void> {
  const comment = reviewComment.trim();
  if (!comment) {
    throw new Error("请填写这张图片需要修改的审核意见。");
  }
  const project = requireProject(projectId);
  markImageNeedsRevision(projectId, imageId, comment);
  const staleFinalDocx = outputPath(projectId, "final_article_with_images.docx");
  if (fs.existsSync(staleFinalDocx)) {
    fs.unlinkSync(staleFinalDocx);
  }
  await runPhase6ImageOutput(project, {
    mode: "generate",
    onlyImageId: imageId,
    reviewComment: comment
  });
  resetImageReviewForGeneratedImages(projectId, imageId);
  updateProjectPhase(projectId, "phase5", "active");
}

export async function approveGeneratedImagesAndCreateFinal(projectId: string): Promise<void> {
  const project = requireProject(projectId);
  approveAllImages(projectId);
  await runPhase6ImageOutput(project, { mode: "insert" });
  const finalDocx = outputPath(projectId, "final_article_with_images.docx");
  if (!fs.existsSync(finalDocx)) {
    throw new Error("图片已确认，但带图 Word 文件未生成。请查看 phase6.log 后重试。");
  }
  updateProjectPhase(projectId, "phase5", "completed");
}

interface SeoMetadata {
  title: string;
  description: string;
  url: string;
}

const seoTitleLabels = ["seo title", "title", "meta title"];
const seoDescriptionLabels = ["description", "meta description"];
const seoUrlLabels = ["url", "url slug", "slug"];

function cleanMetadataValue(value: string): string {
  return value
    .trim()
    .replace(/^[-*]\s+/, "")
    .replace(/\*\*/g, "")
    .replace(/^option\s+[a-z]\s*[:：-]\s*/i, "")
    .replace(/^[：:]\s*/, "")
    .trim();
}

function normalizeMetadataLabel(line: string): string {
  return line
    .trim()
    .replace(/^#+\s*/, "")
    .replace(/^[-*]\s+/, "")
    .replace(/\*\*/g, "")
    .replace(/[：:]\s*.*$/, "")
    .trim()
    .toLowerCase();
}

function isMetadataLabel(label: string, candidates: string[]): boolean {
  const normalized = label.toLowerCase();
  return candidates.some((candidate) => normalized === candidate || normalized.endsWith(` ${candidate}`));
}

function nextMetadataValue(lines: string[], startIndex: number): string {
  for (let index = startIndex + 1; index < lines.length; index += 1) {
    const value = cleanMetadataValue(lines[index]);
    if (!value || value === "---") {
      continue;
    }
    if (/^#{1,6}\s+/.test(value)) {
      return "";
    }
    return value;
  }
  return "";
}

function extractMetadataValue(markdown: string, labels: string[]): string {
  const lines = markdown.split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index].trim();
    const inline = line
      .replace(/^[-*]\s+/, "")
      .replace(/\*\*/g, "")
      .match(/^(.+?)\s*[:：]\s*(.+)$/);
    if (inline && isMetadataLabel(inline[1].trim(), labels)) {
      return cleanMetadataValue(inline[2]);
    }

    const headingLabel = normalizeMetadataLabel(line);
    if (/^#{1,6}\s+/.test(line) && isMetadataLabel(headingLabel, labels)) {
      return nextMetadataValue(lines, index);
    }
  }
  return "";
}

function firstHeading(markdown: string): string {
  const match = markdown.match(/^#\s+(.+)$/m);
  return cleanMetadataValue(match?.[1] || "");
}

function slugifyUrl(value: string): string {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "seo-article";
}

function seoMetadataFromProject(project: Project, articleMarkdown: string): SeoMetadata {
  const outlinePath = outputPath(project.id, phaseOutputs.phase1[0]);
  const outline = fs.existsSync(outlinePath) ? fs.readFileSync(outlinePath, "utf-8") : "";
  const source = `${articleMarkdown}\n\n${outline}`;
  const title =
    extractMetadataValue(source, seoTitleLabels) ||
    firstHeading(articleMarkdown) ||
    project.article_title ||
    project.topic ||
    project.name;
  const isEnglish = (project.language || "").toLowerCase().startsWith("eng");
  const description =
    extractMetadataValue(source, seoDescriptionLabels) ||
    (isEnglish ? "" : project.article_focus) ||
    (isEnglish ? "" : project.recommendation_reason) ||
    `A practical guide to ${project.topic || project.primary_keyword}.`;
  const url =
    extractMetadataValue(source, seoUrlLabels) ||
    slugifyUrl(project.primary_keyword || project.topic || project.name);

  return {
    title: cleanMetadataValue(title),
    description: cleanMetadataValue(description),
    url: cleanMetadataValue(url)
  };
}

function isSeoMetadataLine(line: string): boolean {
  const cleaned = line.trim().replace(/^[-*]\s+/, "").replace(/\*\*/g, "");
  return /^(seo\s+title|title|meta\s+title|description|meta\s+description|url|url\s+slug|slug)\s*[:：]/i.test(cleaned);
}

function removeLeadingSeoMetadata(markdown: string): string {
  const lines = markdown.trim().split(/\r?\n/);
  let index = 0;
  let removedAny = false;
  while (index < lines.length) {
    const line = lines[index].trim();
    if (!line || (removedAny && line === "---")) {
      index += 1;
      continue;
    }
    if (isSeoMetadataLine(line)) {
      removedAny = true;
      index += 1;
      continue;
    }
    break;
  }
  return lines.slice(index).join("\n").trim();
}

function ensureSeoMetadataAtTop(project: Project, markdown: string): string {
  const normalized = extractArticleMarkdownForAudit(markdown);
  const metadata = seoMetadataFromProject(project, normalized);
  const body = removeLeadingSeoMetadata(normalized);
  return [
    `**SEO Title:** ${metadata.title}`,
    `**Description:** ${metadata.description}`,
    `**URL:** ${metadata.url}`,
    "",
    body
  ].join("\n").trim() + "\n";
}

function normalizeFinalArticleForDelivery(project: Project): string {
  const fullArticle = outputPath(project.id, "03_full_article.md");
  const raw = fs.readFileSync(fullArticle, "utf-8");
  const normalized = ensureSeoMetadataAtTop(project, raw);
  if (normalized && normalized.trim() !== raw.trim()) {
    fs.writeFileSync(fullArticle, normalized, "utf-8");
  }
  return fullArticle;
}

function ensureOutputExists(output: string): void {
  if (!fs.existsSync(output)) {
    throw new Error("输出文件未生成。");
  }
}

async function ensureWritingChecklist(project: Project): Promise<string> {
  const checklist = outputPath(project.id, phaseOutputs.phase0[1]);
  if (fs.existsSync(checklist)) {
    return checklist;
  }

  const extractedPath = outputPath(project.id, "extracted_materials.md");
  const briefPath = path.join(getInputsDir(project.id), "article_brief.md");
  const summary = outputPath(project.id, phaseOutputs.phase0[0]);
  if (!fs.existsSync(extractedPath) || !fs.existsSync(briefPath) || !fs.existsSync(summary)) {
    throw new Error("Phase 0 checklist 不存在，请重新运行 Phase 0 以生成 00_writing_checklist.md。");
  }
  await runSkillPrompt(project, phase0ChecklistPromptArgs([extractedPath, briefPath, summary], checklist));
  return checklist;
}

function extractArticleMarkdownForAudit(content: string): string {
  const fenced = content.match(/```(?:markdown|md)?\s*([\s\S]*?)```/i);
  if (fenced?.[1]) {
    return fenced[1].trim();
  }
  const trimmed = content.trim();
  const starts = [
    trimmed.search(/\*\*SEO Title\*\*:/i),
    trimmed.search(/^#\s+/m)
  ].filter((index) => index >= 0);
  if (starts.length > 0) {
    const start = Math.min(...starts);
    return trimmed.slice(start).trim();
  }
  return trimmed;
}

function stripSeoMetadataForWordCount(markdown: string): string {
  return markdown
    .split(/\r?\n/)
    .filter((line) => {
      const normalized = line.trim().replace(/\*\*/g, "").toLowerCase();
      return !/^(seo\s+title|title|description|meta\s+title|meta\s+description|url|url\s+slug|slug)\s*:/.test(normalized);
    })
    .join("\n");
}

function countVisibleArticleWords(markdown: string): number {
  const visibleText = stripSeoMetadataForWordCount(extractArticleMarkdownForAudit(markdown))
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/!\[[^\]]*]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)]\([^)]+\)/g, "$1")
    .replace(/[`*_>#|~=[\]{}()]/g, " ")
    .replace(/^-{3,}$/gm, " ")
    .replace(/\s+/g, " ")
    .trim();
  const latinWords = visibleText.match(/[A-Za-z0-9]+(?:[’'-][A-Za-z0-9]+)*/g) || [];
  const cjkChars = visibleText.match(/[\u3400-\u9fff]/g) || [];
  if (latinWords.length === 0 && cjkChars.length > 0) {
    return cjkChars.length;
  }
  return latinWords.length + Math.round(cjkChars.length / 2);
}

function normalizeMarkdownOutput(filePath: string): void {
  const raw = fs.readFileSync(filePath, "utf-8");
  const fenced = raw.match(/```(?:markdown|md)?\s*([\s\S]*?)```/i);
  if (fenced?.[1]) {
    fs.writeFileSync(filePath, fenced[1].trim(), "utf-8");
  }
}

function splitLongBlock(block: string, maxChars: number): string[] {
  if (block.length <= maxChars) {
    return [block];
  }
  const chunks: string[] = [];
  for (let index = 0; index < block.length; index += maxChars) {
    chunks.push(block.slice(index, index + maxChars).trim());
  }
  return chunks.filter(Boolean);
}

function writeTextFileIfChanged(filePath: string, content: string): void {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, "utf-8") === content) {
    return;
  }
  fs.writeFileSync(filePath, content, "utf-8");
}

function splitArticleForAudit(article: string, maxChars = phase4ChunkMaxChars): string[] {
  const sections = article.split(/\n(?=##\s+)/g).filter((section) => section.trim());
  const chunks: string[] = [];
  let current = "";

  for (const section of sections.length ? sections : [article]) {
    const trimmed = section.trim();
    const candidate = current ? `${current}\n\n${trimmed}` : trimmed;
    if (candidate.length <= maxChars) {
      current = candidate;
      continue;
    }
    if (current) {
      chunks.push(current);
      current = "";
    }
    chunks.push(...splitLongBlock(trimmed, maxChars));
  }

  if (current) {
    chunks.push(current);
  }
  return chunks.filter(Boolean);
}

function preparePhase4Chunks(projectId: string, fullArticlePath: string): string[] {
  const rawArticle = fs.readFileSync(fullArticlePath, "utf-8");
  const article = extractArticleMarkdownForAudit(rawArticle);
  if (!article) {
    throw new Error("Phase 4 审查失败：03_full_article.md 为空。");
  }

  const auditInput = outputPath(projectId, "03_full_article_audit_input.md");
  writeTextFileIfChanged(auditInput, article);

  const chunkDir = path.join(getOutputsDir(projectId), "phase4_audit_chunks");
  fs.mkdirSync(chunkDir, { recursive: true });
  const chunks = splitArticleForAudit(article);
  const activeIndexes = new Set(chunks.map((_, index) => index + 1));
  for (const entry of fs.readdirSync(chunkDir, { withFileTypes: true })) {
    const match = entry.name.match(/^chunk_(\d+)(?:_report)?\.md$/);
    if (entry.isFile() && match && !activeIndexes.has(Number(match[1]))) {
      fs.unlinkSync(path.join(chunkDir, entry.name));
    }
  }
  return chunks.map((chunk, index) => {
    const chunkPath = path.join(chunkDir, `chunk_${String(index + 1).padStart(2, "0")}.md`);
    writeTextFileIfChanged(
      chunkPath,
      [
        "# Phase 4 Article Chunk",
        "",
        `Chunk: ${index + 1}/${chunks.length}`,
        "",
        "## Article Text",
        "",
        chunk
      ].join("\n"),
    );
    return chunkPath;
  });
}

function sectionContent(markdown: string, heading: string): string {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = markdown.match(new RegExp(`##\\s+${escaped}\\s*\\n([\\s\\S]*?)(?=\\n##\\s+|$)`, "i"));
  return match?.[1]?.trim() || "";
}

function meaningfulIssueLines(report: string): string[] {
  return sectionContent(report, "Issues Found")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => line !== "-")
    .filter((line) => !/^-\s*none\.?$/i.test(line))
    .filter((line) => !/no issues found/i.test(line));
}

function remainingQuestionLines(report: string): string[] {
  return sectionContent(report, "Remaining Questions")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => line !== "-")
    .filter((line) => !/^-\s*none\.?$/i.test(line))
    .filter((line) => !/no remaining questions/i.test(line));
}

function passedEvidenceLines(report: string): string[] {
  return sectionContent(report, "Passed Evidence")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => line !== "-")
    .slice(0, 3);
}

function canReusePhase4ChunkReport(reportPath: string, sourceMtimeMs: number): boolean {
  if (!fs.existsSync(reportPath)) {
    return false;
  }
  const stats = fs.statSync(reportPath);
  return stats.size > 0 && stats.mtimeMs >= sourceMtimeMs;
}

interface ChecklistItem {
  id: string;
  text: string;
}

function parseChecklistItems(checklistPath: string): ChecklistItem[] {
  if (!fs.existsSync(checklistPath)) {
    return [];
  }
  const content = fs.readFileSync(checklistPath, "utf-8");
  const items: ChecklistItem[] = [];
  const checkboxPattern = /^\s*-\s*\[.\]\s*(C\d+(?:-\d+)?(?:\.\d+)?)\s+(.+)$/;
  const idPattern = /^\s*-\s*(C\d+(?:-\d+)?(?:\.\d+)?)\s*[|:：]\s*(.+)$/;

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    const checkboxMatch = trimmed.match(checkboxPattern);
    if (checkboxMatch) {
      items.push({ id: checkboxMatch[1], text: checkboxMatch[2].trim() });
      continue;
    }
    const idMatch = trimmed.match(idPattern);
    if (idMatch) {
      items.push({ id: idMatch[1], text: idMatch[2].trim() });
      continue;
    }
  }
  return items;
}

const OPENING_KEYWORDS = [
  "开头", "opening", "first paragraph", "first few paragraphs", "前几段",
  "不在开头", "直接回答读者", "不使用 In this article", "不上来介绍",
  "开头段落", "文章开头", "opening paragraphs",
];

const FAQ_KEYWORDS = [
  "FAQ", "Frequently Asked Questions", "FAQ 模块", "每条 FAQ",
  "FAQ 数量", "FAQ 答案", "直接回答",
];

const CONCLUSION_KEYWORDS = [
  "结尾", "conclusion", "官网链接", "CTA", "最低门槛行动",
  "action over waiting", "hellotalk.com", "轻推",
];

const METADATA_KEYWORDS = [
  "SEO Title", "Description", "URL", "元数据", "metadata",
  "H1 之前", "文件最顶部",
];

const FORBIDDEN_KEYWORDS = [
  "禁用词", "禁用符号", "forbidden words", "forbidden punctuation",
  "零容忍", "全文不出现", "Tandem", "VPN", "Taiwan",
  "scammers", "frauds", "dating", "政治",
];

const WORD_COUNT_KEYWORDS = [
  "字数", "word count", "1200", "1600", "visible article words",
];

const IMAGE_KEYWORDS = [
  "图片", "image", "IMAGE_PLACEHOLDER", "[IMAGE_1]", "AI Prompt",
  "markdown 图片语法", "image description", "image planning",
];

const BRAND_DATA_KEYWORDS = [
  "官方数据", "70M+", "200+ countries", "1B+ messages",
  "90% of core features", "数据分散", "2–3 条",
];

const BRAND_FEATURE_KEYWORDS = [
  "四大功能模块", "Chat-based Learning", "Moments",
  "Voicerooms & Livestreams", "AI Learning Tools", "功能模块全部出现",
];

function matchesKeywords(text: string, keywords: string[]): boolean {
  const lower = text.toLowerCase();
  return keywords.some((kw) => lower.includes(kw.toLowerCase()));
}

function classifyChecklistItem(item: ChecklistItem): string {
  const text = item.text;
  if (matchesKeywords(text, OPENING_KEYWORDS)) return "opening";
  if (matchesKeywords(text, FAQ_KEYWORDS)) return "faq";
  if (matchesKeywords(text, CONCLUSION_KEYWORDS)) return "conclusion";
  if (matchesKeywords(text, METADATA_KEYWORDS)) return "metadata";
  if (matchesKeywords(text, FORBIDDEN_KEYWORDS)) return "forbidden";
  if (matchesKeywords(text, WORD_COUNT_KEYWORDS)) return "word_count";
  if (matchesKeywords(text, IMAGE_KEYWORDS)) return "image";
  if (matchesKeywords(text, BRAND_DATA_KEYWORDS)) return "brand_data";
  if (matchesKeywords(text, BRAND_FEATURE_KEYWORDS)) return "brand_feature";
  return "local";
}

function runGlobalChecks(articlePath: string, checklistPath: string): string[] {
  const issues: string[] = [];
  if (!fs.existsSync(articlePath)) {
    return issues;
  }
  const raw = fs.readFileSync(articlePath, "utf-8");
  const articleLines = raw.split(/\r?\n/);

  const items = parseChecklistItems(checklistPath);
  const globalItems = items.filter((item) => classifyChecklistItem(item) !== "local");

  for (const item of globalItems) {
    const scope = classifyChecklistItem(item);

    if (scope === "opening") {
      const openingLines: string[] = [];
      let inOpening = true;
      for (const line of articleLines) {
        const trimmed = line.trim();
        if (/^##\s+/.test(trimmed)) inOpening = false;
        if (inOpening && trimmed) openingLines.push(trimmed.toLowerCase());
      }
      const openingText = openingLines.join(" ");
      if (matchesKeywords(item.text, ["HelloTalk", "hellotalk", "产品", "品牌"]) && openingText.includes("hellotalk")) {
        issues.push(`- ${item.id} | 开头段落 | 开头段落出现了 HelloTalk，应在中后段自然引出 | 将 HelloTalk 相关内容移到文章中后段 | severity: high`);
      }
      if (matchesKeywords(item.text, ["直接回答", "核心问题", "In this article"]) && /in this article/i.test(openingText)) {
        issues.push(`- ${item.id} | 开头段落 | 开头使用了模板句 "In this article" | 改为直接回答读者问题 | severity: medium`);
      }
    }

    if (scope === "metadata") {
      if (matchesKeywords(item.text, ["SEO Title"]) && !raw.includes("**SEO Title**:") && !raw.includes("SEO Title:")) {
        issues.push(`- ${item.id} | 元数据 | 缺少 SEO Title | 在 H1 之前添加 SEO Title | severity: high`);
      }
      if (matchesKeywords(item.text, ["Description"]) && !raw.includes("**Description**:") && !raw.includes("Description:")) {
        issues.push(`- ${item.id} | 元数据 | 缺少 Description | 在 H1 之前添加 Description | severity: high`);
      }
      if (matchesKeywords(item.text, ["URL"]) && !raw.includes("**URL**:") && !raw.includes("URL:")) {
        issues.push(`- ${item.id} | 元数据 | 缺少 URL slug | 在 H1 之前添加 URL slug | severity: medium`);
      }
    }

    if (scope === "forbidden") {
      const forbiddenTerms = [
        { pattern: /\bTandem\b/i, term: "Tandem" },
        { pattern: /\bVPN\b/i, term: "VPN" },
        { pattern: /\bTaiwan\b/i, term: "Taiwan" },
        { pattern: /\bscammers?\b/i, term: "scammer" },
        { pattern: /\bfrauds?\b/i, term: "fraud" },
        { pattern: /\bdating\b/i, term: "dating" },
      ];
      for (const { pattern, term } of forbiddenTerms) {
        if (matchesKeywords(item.text, [term]) && pattern.test(raw)) {
          issues.push(`- ${item.id} | 全文 | 出现禁用词 "${term}" | 删除或替换为合规表述 | severity: high`);
        }
      }
    }

    if (scope === "image") {
      const imagePatterns = [
        { pattern: /IMAGE_PLACEHOLDER/i, name: "IMAGE_PLACEHOLDER" },
        { pattern: /\[IMAGE_\d+\]/, name: "[IMAGE_N]" },
        { pattern: /AI Prompt:/i, name: "AI Prompt:" },
        { pattern: /!\[[^\]]*\]\([^)]*\)/, name: "markdown image syntax" },
      ];
      for (const { pattern, name } of imagePatterns) {
        if (pattern.test(raw)) {
          issues.push(`- ${item.id} | 全文 | 正文中残留图片相关语法（${name}） | 删除图片占位符或 markdown 图片语法 | severity: medium`);
          break;
        }
      }
    }
  }

  const hasSeoTitle = raw.includes("**SEO Title**:") || raw.includes("SEO Title:");
  const hasDescription = raw.includes("**Description**:") || raw.includes("Description:");
  const hasUrl = raw.includes("**URL**:") || raw.includes("URL:");
  const metadataItems = globalItems.filter((item) => classifyChecklistItem(item) === "metadata");
  if (metadataItems.length === 0) {
    if (!hasSeoTitle) issues.push("- 元数据 | 元数据 | 缺少 SEO Title | 在 H1 之前添加 SEO Title | severity: high");
    if (!hasDescription) issues.push("- 元数据 | 元数据 | 缺少 Description | 在 H1 之前添加 Description | severity: high");
    if (!hasUrl) issues.push("- 元数据 | 元数据 | 缺少 URL slug | 在 H1 之前添加 URL slug | severity: medium");
  }

  return issues;
}

function mergePhase4ChunkReports(chunkReportPaths: string[], output: string, articleWordCount: number, articlePath: string, checklistPath: string, wordRange?: { min: number; max: number }): void {
  const minWords = wordRange?.min ?? DEFAULT_MIN_WORDS;
  const maxWords = wordRange?.max ?? DEFAULT_MAX_WORDS;
  const chunkReports = chunkReportPaths.map((reportPath, index) => ({
    index: index + 1,
    path: reportPath,
    content: fs.readFileSync(reportPath, "utf-8")
  }));
  const issueGroups = chunkReports.map((report) => ({
    ...report,
    issues: meaningfulIssueLines(report.content),
    questions: remainingQuestionLines(report.content),
    passedEvidence: passedEvidenceLines(report.content)
  }));
  const globalIssues = runGlobalChecks(articlePath, checklistPath);
  const hasChunkIssues = issueGroups.some((report) => report.issues.length > 0);
  const hasIssues = hasChunkIssues || globalIssues.length > 0;
  const hasQuestions = issueGroups.some((report) => report.questions.length > 0);
  const lengthIssue =
    articleWordCount < minWords
      ? `- C05-Length | 全文 | 当前可见正文约 ${articleWordCount} words，低于 ${minWords}-${maxWords} words 目标范围 | 补充必要的具体信息，但不要增加空泛段落 | severity: medium`
      : articleWordCount > maxWords
        ? `- C05-Length | 全文 | 当前可见正文约 ${articleWordCount} words，超过 ${minWords}-${maxWords} words 目标范围 | 压缩重复示例、泛泛建议、长转场和过度产品说明 | severity: high`
        : "";
  const checklistPassed = !hasIssues && !hasQuestions && !lengthIssue;

  const lines = [
    `checklist_passed: ${checklistPassed ? "true" : "false"}`,
    "",
    "# Checklist Report",
    "",
    "## 1. Passed Items",
    "",
    `- 已使用 Phase 0 固定 checklist 对全文进行 ${chunkReports.length} 个分块审查。`,
    lengthIssue
      ? `- 字数检查未通过：全文可见正文约 ${articleWordCount} words；目标范围为 ${minWords}-${maxWords} words。详见 Issues Found。`
      : `- 字数检查通过：全文可见正文约 ${articleWordCount} words；目标范围为 ${minWords}-${maxWords} words。`,
    "- Phase 4 合并步骤由后端本地完成，未重新生成或修改 checklist 标准。",
    "- 详细逐段审查记录见 `outputs/phase4_audit_chunks/`。"
  ];

  for (const report of issueGroups) {
    if (report.passedEvidence.length > 0) {
      lines.push(`- Chunk ${report.index}: ${report.passedEvidence.join("；")}`);
    }
  }

  lines.push("", "## 2. Issues Found", "");
  if (!hasIssues && !lengthIssue) {
    lines.push("- None");
  } else {
    if (lengthIssue) {
      lines.push("### Overall Length");
      lines.push("");
      lines.push(lengthIssue);
      lines.push("");
    }
    if (globalIssues.length > 0) {
      lines.push("### Global Rules");
      lines.push("");
      lines.push(...globalIssues);
      lines.push("");
    }
    for (const report of issueGroups) {
      if (report.issues.length === 0) {
        continue;
      }
      lines.push(`### Chunk ${report.index}`);
      lines.push("");
      lines.push(...report.issues);
      lines.push("");
    }
  }

  lines.push("## 3. Revised Version Notes", "");
  lines.push("- Phase 4 本轮只执行固定 checklist 审查和报告合并，没有在合并步骤中改写 `03_full_article.md`。");
  if (hasIssues || lengthIssue) {
    lines.push("- 当前报告存在待修订项；请根据 Issues Found 修订正文后重新运行 Phase 4。");
  } else {
    lines.push("- 未发现需要修订的问题。");
  }

  lines.push("", "## 4. Remaining Questions", "");
  if (!hasQuestions) {
    lines.push("- None");
  } else {
    for (const report of issueGroups) {
      if (report.questions.length === 0) {
        continue;
      }
      lines.push(`### Chunk ${report.index}`);
      lines.push(...report.questions);
      lines.push("");
    }
  }

  fs.writeFileSync(output, lines.join("\n").trimEnd() + "\n", "utf-8");
}

async function runPhase4(project: Project): Promise<string> {
  const writingChecklist = await ensureWritingChecklist(project);
  const full = normalizeFinalArticleForDelivery(project);
  const output = outputPath(project.id, phaseOutputs.phase4[0]);
  const articleWordCount = countVisibleArticleWords(fs.readFileSync(full, "utf-8"));
  await runSkillPrompt(
    project,
    phase4PromptArgs("phase4_checklist.md", [writingChecklist, full], output),
    "auditor"
  );
  ensureOutputExists(output);
  return output;
}

export async function runPhase4Chunked(projectId: string): Promise<void> {
  const project = requireProject(projectId);
  const state = readProjectState(projectId);
  const runId = createPhaseRun(projectId, "phase4", "running", "chunked audit");
  setPhaseStatus(projectId, "phase4", "running");
  updateProjectPhase(projectId, "phase4", "active");

  try {
    const writingChecklist = await ensureWritingChecklist(project);
    const full = normalizeFinalArticleForDelivery(project);
    const output = outputPath(project.id, phaseOutputs.phase4[0]);
    const articleWordCount = countVisibleArticleWords(fs.readFileSync(full, "utf-8"));
    const chunkPaths = preparePhase4Chunks(project.id, full);
    const reportDir = path.join(getOutputsDir(project.id), "phase4_audit_chunks");
    const chunkReportPaths: string[] = [];
    const sourceMtimeMs = Math.max(fs.statSync(full).mtimeMs, fs.statSync(writingChecklist).mtimeMs);

    for (const [index, chunkPath] of chunkPaths.entries()) {
      const chunkReport = path.join(reportDir, `chunk_${String(index + 1).padStart(2, "0")}_report.md`);
      const chunkSourceMtimeMs = Math.max(sourceMtimeMs, fs.statSync(chunkPath).mtimeMs);
      if (!canReusePhase4ChunkReport(chunkReport, chunkSourceMtimeMs)) {
        await runSkillPrompt(
          project,
          phase4PromptArgs("phase4_chunk_check.md", [writingChecklist, chunkPath], chunkReport),
          "auditor"
        );
      }
      ensureOutputExists(chunkReport);
      chunkReportPaths.push(chunkReport);
    }

    const wordRange = getWordCountRange(projectId);
    mergePhase4ChunkReports(chunkReportPaths, output, articleWordCount, full, writingChecklist, wordRange);
    ensureOutputExists(output);
    setPhaseStatus(projectId, "phase4", "waiting_review");
    updatePhaseRun(runId, "waiting_review", path.relative(getProjectDir(projectId), output).replace(/\\/g, "/"));
    updateProjectPhase(projectId, "phase4", "active");
  } catch (error) {
    const message = sanitizeError(error);
    setPhaseStatus(projectId, "phase4", "failed", message);
    updatePhaseRun(runId, "failed", "", message);
    updateProjectPhase(projectId, "phase4", "failed");
    throw new Error(message);
  }
}

async function runPromptPhase(project: Project, phase: PhaseId): Promise<string> {
  const outputs = getOutputsDir(project.id);
  const output = path.join(outputs, phaseOutputs[phase][0]);
  const summary = outputPath(project.id, phaseOutputs.phase0[0]);
  const writingChecklist = await ensureWritingChecklist(project);
  const outline = outputPath(project.id, phaseOutputs.phase1[0]);
  const firstTwo = outputPath(project.id, phaseOutputs.phase2[0]);
  const full = outputPath(project.id, phaseOutputs.phase3[0]);
  const checklist = outputPath(project.id, phaseOutputs.phase4[0]);
  const brief = path.join(getInputsDir(project.id), "article_brief.md");
  const extracted = outputPath(project.id, "extracted_materials.md");
  const outlineTemplate = skillPath("templates", "outline_template.md");

  const inputMap: Record<PhaseId, string[]> = {
    phase0: [],
    phase1: [summary, brief, extracted, outlineTemplate],
    phase2: [summary, outline, writingChecklist, languageContentRequirementsPath()],
    phase3: [summary, outline, firstTwo, brief, languageContentRequirementsPath()],
    phase4: [writingChecklist, full],
    phase5: [summary, full, checklist]
  };

  if (phase === "phase2") {
    const draft = outputPath(project.id, "02_first_two_sections_draft.md");
    await runSkillPrompt(project, commonPromptArgs(project.id, phase, inputMap[phase], draft), "writing");
    ensureOutputExists(draft);
    await runSkillPrompt(
      project,
      phase2AuditorPolishPromptArgs([writingChecklist, summary, outline, draft], output),
      "auditor"
    );
    return output;
  }

  if (phase === "phase4") {
    return runPhase4(project);
  }

  const args = commonPromptArgs(project.id, phase, inputMap[phase], output);
  await runSkillPrompt(project, args, "writing");

  // Phase 3: validate word count after generation
  if (phase === "phase3") {
    const articleContent = fs.readFileSync(output, "utf-8");
    const wordCount = countVisibleArticleWords(articleContent);
    const wordRange = getWordCountRange(project.id);
    if (wordCount < wordRange.min) {
      // Attempt word count repair (up to 2 retries)
      for (let attempt = 0; attempt < 2; attempt++) {
        const repairInput = outputPath(project.id, `phase3_repair_input_${attempt}.md`);
        fs.writeFileSync(repairInput, [
          "# Word Count Repair",
          "",
          `Current word count: ${wordCount} words`,
          `Target range: ${wordRange.min}-${wordRange.max} words`,
          `Deficit: ${wordRange.min - wordCount} words below minimum`,
          "",
          "## Current Article",
          "",
          articleContent,
        ].join("\n"), "utf-8");
        try {
          await runSkillPrompt(project, [
            "scripts/run_prompt.py",
            "--prompt", "prompts/phase3_length_repair.md",
            "--input", repairInput,
            "--output", output,
          ], "writing");
          const repaired = fs.readFileSync(output, "utf-8");
          const repairedCount = countVisibleArticleWords(repaired);
          if (repairedCount >= wordRange.min) break;
        } catch {
          // repair failed, keep original
        }
      }
    }
  }

  return output;
}

export async function runPhase(projectId: string, phase: PhaseId): Promise<void> {
  const project = requireProject(projectId);
  const state = readProjectState(projectId);
  assertPhaseCanRun(state, phase);
  const phaseState = state.phases[phase];
  if (phaseState.status === "running" || phaseState.status === "waiting_review" || phaseState.status === "approved") {
    return;
  }
  const invocation = buildInvocationPrompt(projectId, phase);
  const runId = createPhaseRun(projectId, phase, "running", invocation);
  setPhaseStatus(projectId, phase, "running");
  updateProjectPhase(projectId, phase, "active");

  try {
    const output = phase === "phase0" ? await runPhase0(project) : phase === "phase5" ? await runPhase5(project) : await runPromptPhase(project, phase);
    ensureOutputExists(output);
    if (requiresManualReview(phase)) {
      setPhaseStatus(projectId, phase, "waiting_review");
      updatePhaseRun(runId, "waiting_review", path.relative(getProjectDir(projectId), output).replace(/\\/g, "/"));
      updateProjectPhase(projectId, phase, "active");
    } else {
      const nextState = approvePhaseInState(projectId, phase);
      updatePhaseRun(runId, "approved");
      updateProjectPhase(projectId, nextState.currentPhase, "active");
    }
  } catch (error) {
    const message = sanitizeError(error);
    setPhaseStatus(projectId, phase, "failed", message);
    updatePhaseRun(runId, "failed", "", message);
    updateProjectPhase(projectId, phase, "failed");
    throw new Error(message);
  }
}

export async function revisePhase(projectId: string, phase: PhaseId, userComment: string): Promise<void> {
  if (!requiresManualReview(phase)) {
    throw new Error("该阶段不需要人工审查，不能提交修改意见。");
  }
  const project = requireProject(projectId);
  if (phase === "phase5") {
    await revisePhase5(project, userComment);
    return;
  }
  const currentOutput = readOutputForPhase(projectId, phase);
  if (!currentOutput) {
    throw new Error("当前阶段还没有可修订的输出。");
  }
  const output = outputPath(projectId, phaseOutputs[phase].find((file) => file.endsWith(".md")) || phaseOutputs[phase][0]);
  const revisionPrompt = outputPath(projectId, `revise_${phase}_prompt.md`);
  fs.writeFileSync(
    revisionPrompt,
    [
      `# Revise ${phase}`,
      "",
      "请使用 SEO Article Writer Skill 根据用户修改意见修订当前阶段输出。",
      "写作规范仍然是最高优先级。如果用户意见和规范冲突，请使用 Skill 中的冲突处理格式，不要绕过规范。",
      "",
      "## 用户修改意见",
      "",
      userComment,
      "",
      "## 输出要求",
      "",
      `请更新 ${path.basename(output)}。完成后停止，不要进入下一阶段。`
    ].join("\n"),
    "utf-8"
  );

  const runId = createPhaseRun(projectId, phase, "running", userComment);
  setPhaseStatus(projectId, phase, "running");
  try {
    const summary = outputPath(projectId, "00_material_reading_summary.md");
    await runSkillPrompt(
      project,
      commonPromptArgs(projectId, phase, [revisionPrompt, summary, output], output)
    );
    ensureOutputExists(output);
    setPhaseStatus(projectId, phase, "waiting_review");
    createReviewComment(projectId, phase, userComment, path.relative(getProjectDir(projectId), output).replace(/\\/g, "/"));
    updatePhaseRun(runId, "waiting_review", path.relative(getProjectDir(projectId), output).replace(/\\/g, "/"));
    updateProjectPhase(projectId, phase, "active");
  } catch (error) {
    const message = sanitizeError(error);
    setPhaseStatus(projectId, phase, "failed", message);
    updatePhaseRun(runId, "failed", "", message);
    updateProjectPhase(projectId, phase, "failed");
    throw new Error(message);
  }
}

async function revisePhase5(project: Project, userComment: string): Promise<void> {
  const projectId = project.id;
  const summary = outputPath(projectId, "00_material_reading_summary.md");
  const writingChecklist = await ensureWritingChecklist(project);
  const fullArticle = outputPath(projectId, "03_full_article.md");
  const phase4AuditSummary = writePhase5RevisionAuditSummary(projectId);

  if (!fs.existsSync(fullArticle)) {
    throw new Error("Phase 5 还没有可修订的最终正文，请先运行 Phase 5。");
  }
  if (!phase4AuditSummary) {
    throw new Error("Phase 4 审查报告不存在，不能在 Phase 5 修正文稿。请先重新运行 Phase 4。");
  }

  const revisionPrompt = outputPath(projectId, "revise_phase5_prompt.md");
  fs.writeFileSync(
    revisionPrompt,
    [
      "# Phase 5 Human Review Comment",
      "",
      "请根据以下人工审查意见修订最终正文。",
      "同时必须参考 `phase5_revision_audit_summary.md` 中整理出的 Phase 4 审查意见。",
      "修订输入中只能以当前最新 `03_full_article.md` 作为正文来源；不要使用旧版本正文或旧 chunk 正文改写当前文章。",
      "写作规范、固定 checklist、Phase 4 审查意见和品牌红线仍然是最高优先级。",
      "如果人工意见与规范冲突，请采用最安全、合规的替代写法。",
      "",
      "## 人工审查意见",
      "",
      userComment,
      "",
      "## Phase 4 审查意见使用要求",
      "",
      "- 修正文稿时要同时解决人工意见和 `phase5_revision_audit_summary.md` 里仍然成立的问题。",
      "- Phase 4 摘要只作为问题清单和修复方向，不是正文来源。",
      "- 如果 Phase 4 摘要中的某条意见与人工意见冲突，请优先遵守写作规范和品牌红线。",
      "- 不要在正文后附解释、审查报告或修订说明，只输出修订后的完整正文。",
      "- 修订完成后系统会重新进入 Phase 4 查验，因此本轮必须尽量一次性修正可确认的问题。",
      "",
      "## 输出要求",
      "",
      "- 覆盖更新 `03_full_article.md`。",
      "- 不要生成 Word 文件、图片计划、图片提示词或任何 Phase 6 输出。",
      "- 完成后停止，系统会回到 Phase 4 重新查验。"
    ].join("\n"),
    "utf-8"
  );

  const runId = createPhaseRun(projectId, "phase5", "running", userComment);
  setPhaseStatus(projectId, "phase5", "running");
  updateProjectPhase(projectId, "phase5", "active");

  try {
    await runSkillPrompt(
      project,
      promptArgs("phase5_revise_article.md", [revisionPrompt, summary, writingChecklist, phase4AuditSummary, fullArticle], fullArticle),
      "writing"
    );
    ensureOutputExists(fullArticle);

    await runSkillPrompt(
      project,
      promptArgs("phase5_stabilize_revision.md", [revisionPrompt, summary, writingChecklist, phase4AuditSummary, fullArticle], fullArticle),
      "writing"
    );
    ensureOutputExists(fullArticle);

    clearPhase4AuditReports(projectId);
    clearDeliveryOutputs(projectId);
    rewindToPhase4AfterPhase5Revision(projectId);

    const responsePath = path.relative(getProjectDir(projectId), fullArticle).replace(/\\/g, "/");
    createReviewComment(projectId, "phase5", userComment, responsePath);
    updatePhaseRun(runId, "approved", responsePath);
    updateProjectPhase(projectId, "phase4", "active");
  } catch (error) {
    const message = sanitizeError(error);
    setPhaseStatus(projectId, "phase5", "failed", message);
    updatePhaseRun(runId, "failed", "", message);
    updateProjectPhase(projectId, "phase5", "failed");
    throw new Error(message);
  }
}

export async function approvePhase(projectId: string, phase: PhaseId): Promise<void> {
  const state = readProjectState(projectId);
  assertPhaseCanApprove(state, phase);
  if (phase === "phase5") {
    const project = requireProject(projectId);
    const configPath = writeImageGenerationConfig(project);
    try {
      await runPhase55ImagePlanning(project, configPath);
    } catch (error) {
      const message = sanitizeError(error);
      fs.appendFileSync(
        outputPath(projectId, "image_planning.log"),
        [
          `[${new Date().toISOString()}] phase5_5_image_planning failed`,
          message,
          ""
        ].join("\n"),
        "utf-8"
      );
    }
    await generateFinalDocx(project, true);
  }
  const nextState = approvePhaseInState(projectId, phase);
  const nextStatus = phase === "phase5" ? "completed" : "active";
  updateProjectPhase(projectId, nextState.currentPhase, nextStatus);
}

export function getReadableOutput(projectId: string, phase: PhaseId): string {
  return readOutputForPhase(projectId, phase);
}

export function readRelativeFile(projectId: string, relativePath: string): string {
  return readProjectFile(projectId, relativePath);
}
