import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { createProject, listProjects } from "@/lib/db";
import { ensureProjectDirs, saveUpload, writeArticleBrief } from "@/lib/fileStorage";
import { createInitialProjectState, writeProjectState } from "@/lib/projectState";
import {
  copySharedFilesToProject,
  getSharedExampleArticleFiles,
  getSharedWritingGuidelineFiles,
  replaceSharedUploads
} from "@/lib/sharedFiles";
import { ImagePlanningMode, Project } from "@/lib/types";
import {
  asImageProvider,
  asProvider,
  optionalText,
  parseSecondaryKeywords,
  requireText,
  resolveImageModelSelection,
  sanitizeError,
  slugifyName
} from "@/lib/validators";

export const runtime = "nodejs";

export async function GET() {
  return NextResponse.json({ projects: listProjects() });
}

function isUploadedFile(value: FormDataEntryValue | null): value is File {
  return Boolean(value && typeof value !== "string" && value.size > 0);
}

function uploadedFiles(values: FormDataEntryValue[]): File[] {
  return values.filter((value): value is File => typeof value !== "string" && value.size > 0);
}

function buildArticleBriefMarkdown(project: Project, imageRequirements: string, extraNotes: string): string {
  return [
    "# Article Brief",
    "",
    `- Project name: ${project.name}`,
    `- Article title: ${project.article_title || "To be generated by SEO Article Writer Skill in Phase 1."}`,
    `- Topic: ${project.topic}`,
    `- Primary keyword: ${project.primary_keyword}`,
    `- Secondary keywords: ${project.secondary_keywords || "To be generated by SEO Article Writer Skill in Phase 1 based on the primary keyword, search intent, examples, and writing guidelines."}`,
    `- Article focus: ${project.article_focus}`,
    `- Recommendation reason: ${project.recommendation_reason}`,
    `- Target audience: ${project.target_audience || "To be inferred by SEO Article Writer Skill from the brief, keywords, examples, and writing guidelines."}`,
    `- Search intent: ${project.search_intent || "To be inferred by SEO Article Writer Skill during Phase 0 / Phase 1."}`,
    `- Language: ${project.language}`,
    `- Brand name: ${project.brand_name}`,
    `- Deferred image requirements for Phase 5.5 only: ${imageRequirements}`,
    `- Extra notes: ${extraNotes || "None"}`
  ].join("\n");
}

async function resolveWritingGuidelineForProject(projectId: string, formData: FormData): Promise<string> {
  const uploadedGuideline = formData.get("writingGuidelineFile");
  const sharedGuidelines = isUploadedFile(uploadedGuideline)
    ? await replaceSharedUploads("writing-guidelines", [uploadedGuideline], "guideline_")
    : getSharedWritingGuidelineFiles();

  if (sharedGuidelines.length === 0) {
    throw new Error("请先上传写作规范。上传一次后，后续项目会自动复用。");
  }

  return copySharedFilesToProject(projectId, sharedGuidelines.slice(0, 1), "guideline_")[0];
}

async function resolveExamplesForProject(projectId: string, formData: FormData): Promise<string[]> {
  const examples = uploadedFiles(formData.getAll("exampleArticleFiles"));
  const sharedExamples = examples.length > 0
    ? await replaceSharedUploads("examples", examples, "example_")
    : getSharedExampleArticleFiles();

  return copySharedFilesToProject(projectId, sharedExamples, "example_");
}

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const projectName = requireText(formData.get("projectName"), "项目名称");
    const id = `${slugifyName(projectName)}-${randomUUID().slice(0, 8)}`;
    ensureProjectDirs(id);

    const now = new Date().toISOString();
    const writingProvider = asProvider(formData.get("writingProvider") ?? formData.get("provider"));
    const writingModelName = requireText(formData.get("writingModelName") ?? formData.get("modelName"), "写作/批改模型名称");
    const writingBaseUrl = optionalText(formData.get("writingBaseUrl") ?? formData.get("baseUrl"));
    const writingTemperature = Number(optionalText(formData.get("writingTemperature") ?? formData.get("temperature")) || 0.7);
    const auditorProvider = formData.get("auditorProvider") ? asProvider(formData.get("auditorProvider")) : writingProvider;
    const auditorModelName = optionalText(formData.get("auditorModelName")) || writingModelName;
    const auditorBaseUrl = optionalText(formData.get("auditorBaseUrl")) || writingBaseUrl;
    const auditorTemperature = Number(optionalText(formData.get("auditorTemperature")) || 0.2);
    const enableImageGeneration = formData.getAll("enableImageGeneration").map(String).includes("true");
    const imageProvider = asImageProvider(formData.get("imageProvider"));
    const { imageModelDisplayName, imageModelId } = resolveImageModelSelection(
      imageProvider,
      formData.get("imageModelDisplayName") ?? formData.get("imageModelName"),
      formData.get("imageModelId")
    );
    const imageModelName = imageModelDisplayName;
    const imageEndpointId = optionalText(formData.get("imageEndpointId"));
    const imageUseEndpointId = formData.getAll("imageUseEndpointId").map(String).includes("true");
    const imageBaseUrl = optionalText(formData.get("imageBaseUrl"));
    const imageTemperature = Number(optionalText(formData.get("imageTemperature")) || 0.2);
    const imageSkillPath =
      optionalText(formData.get("imageSkillPath")) || "../skills/hellotalk-blog-image-planner-v2.skill";
    const imageOutputFormat = optionalText(formData.get("imageOutputFormat")) || "png";
    const imageAspectRatioDefault = optionalText(formData.get("imageAspectRatioDefault")) || "16:9";
    const imageRetryCount = Number(optionalText(formData.get("imageRetryCount")) || 2);
    const imageInsertMode = optionalText(formData.get("imageInsertMode")) || "placeholder";
    const imageCountDefault = Number(optionalText(formData.get("imageCountDefault")) || 3);
    const imageAllowNonCompliantImages = formData.getAll("imageAllowNonCompliantImages").map(String).includes("true");
    const imagePlanningMode = (optionalText(formData.get("imagePlanningMode")) || "auto") as ImagePlanningMode;
    const secondaryKeywords = parseSecondaryKeywords(optionalText(formData.get("secondaryKeywords")));
    const imageRequirements = optionalText(formData.get("imageRequirements"));
    const extraNotes = optionalText(formData.get("extraNotes"));

    const writingGuideline = await resolveWritingGuidelineForProject(id, formData);
    const exampleArticleFiles = await resolveExamplesForProject(id, formData);

    const topicRequirementFile = formData.get("topicRequirementFile");
    const topicRequirementPath =
      isUploadedFile(topicRequirementFile)
        ? await saveUpload(id, topicRequirementFile, "topic_")
        : "";

    const project: Project = {
      id,
      name: projectName,
      article_title: optionalText(formData.get("articleTitle")),
      topic: requireText(formData.get("topic"), "选题"),
      primary_keyword: requireText(formData.get("primaryKeyword"), "主关键词"),
      secondary_keywords: secondaryKeywords.join(", "),
      article_focus: requireText(formData.get("articleFocus"), "文章重点"),
      recommendation_reason: requireText(formData.get("recommendationReason"), "推荐理由"),
      target_audience: optionalText(formData.get("targetAudience")),
      search_intent: optionalText(formData.get("searchIntent")),
      language: optionalText(formData.get("language")) || "English",
      brand_name: optionalText(formData.get("brandName")),
      writing_provider: writingProvider,
      writing_model_name: writingModelName,
      writing_base_url: writingBaseUrl,
      writing_temperature: writingTemperature,
      writing_max_tokens: 0,
      auditor_provider: auditorProvider,
      auditor_model_name: auditorModelName,
      auditor_base_url: auditorBaseUrl,
      auditor_temperature: auditorTemperature,
      auditor_max_tokens: 0,
      enable_image_generation: enableImageGeneration,
      image_provider: imageProvider,
      image_model_display_name: imageModelDisplayName,
      image_model_name: imageModelName,
      image_model_id: imageModelId,
      image_endpoint_id: imageEndpointId,
      image_use_endpoint_id: imageUseEndpointId,
      image_base_url: imageBaseUrl,
      image_temperature: imageTemperature,
      image_skill_path: imageSkillPath,
      image_output_format: imageOutputFormat,
      image_aspect_ratio_default: imageAspectRatioDefault,
      image_retry_count: Number.isFinite(imageRetryCount) ? imageRetryCount : 2,
      image_insert_mode: imageInsertMode,
      image_count_default: Number.isFinite(imageCountDefault) ? imageCountDefault : 3,
      image_allow_non_compliant_images: imageAllowNonCompliantImages,
      image_planning_mode: imagePlanningMode,
      provider: writingProvider,
      model_name: writingModelName,
      base_url: writingBaseUrl,
      temperature: writingTemperature,
      max_tokens: 0,
      current_phase: "phase0",
      status: "active",
      created_at: now,
      updated_at: now
    };

    createProject(project);
    const state = createInitialProjectState(project, {
      writingGuidelineFile: writingGuideline,
      exampleArticleFiles,
      topicRequirementFile: topicRequirementPath,
      imageRequirements,
      extraNotes
    });
    writeProjectState(state);
    writeArticleBrief(id, buildArticleBriefMarkdown(project, imageRequirements, extraNotes));

    return NextResponse.json({ projectId: id }, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: sanitizeError(error) }, { status: 400 });
  }
}
